<?xml-stylesheet type='text/xsl' href='../resultface.xsl'?><testsuite tests="13" failures="0" errors="4" skipped="0" time="0.627" name="module 'hty_inte'">
  <testcase time="0.248" name="hty_inte_tests:0 tests_in_fixture (accesslog:basic)">
    <error type="throw">
::in function hty_inte:'-check_asserts/5-fun-3-'/1 (src/test/erlang/hty_inte.erl, line 127)
in call from lists:foreach/2 (lists.erl, line 1337)
in call from lists:map/2 (lists.erl, line 1238)
in call from hty_inte:run/2 (src/test/erlang/hty_inte.erl, line 13)
**throw:{error,["Expected ","200"," but got ","404"]}
    </error>
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.006" name="hty_inte_tests:0 tests_in_fixture (login:redirected_to_login)">
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.007" name="hty_inte_tests:0 tests_in_fixture (login:get_rootfile)">
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.014" name="hty_inte_tests:0 tests_in_fixture (static_listing:list_root)">
    <error type="throw">
::in function hty_inte:'-check_asserts/5-fun-3-'/1 (src/test/erlang/hty_inte.erl, line 127)
in call from lists:foreach/2 (lists.erl, line 1337)
in call from lists:map/2 (lists.erl, line 1238)
in call from hty_inte:run/2 (src/test/erlang/hty_inte.erl, line 13)
**throw:{error,["Expected ",
        "&lt;dir&gt;&lt;file&gt;index.html&lt;/file&gt;&lt;file&gt;rootfile.html&lt;/file&gt;&lt;file&gt;rootfile1.html&lt;/file&gt;&lt;/dir&gt;\n",
        " but got ",
        "&lt;dir&gt;&lt;file&gt;index.html&lt;/file&gt;&lt;file&gt;subfolder&lt;/file&gt;&lt;file&gt;rootfile.html&lt;/file&gt;&lt;file&gt;rootfile1.html&lt;/file&gt;&lt;/dir&gt;"]}
    </error>
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.012" name="hty_inte_tests:0 tests_in_fixture (static_listing:list_sub)">
    <error type="throw">
::in function hty_inte:'-check_asserts/5-fun-3-'/1 (src/test/erlang/hty_inte.erl, line 127)
in call from lists:foreach/2 (lists.erl, line 1337)
in call from lists:map/2 (lists.erl, line 1238)
in call from hty_inte:run/2 (src/test/erlang/hty_inte.erl, line 13)
**throw:{error,["Expected ",
        "&lt;dir&gt;&lt;file&gt;index.html&lt;/file&gt;&lt;file&gt;subfile.html&lt;/file&gt;&lt;file&gt;subfile1.html&lt;/file&gt;&lt;/dir&gt;\n",
        " but got ",
        "&lt;dir&gt;&lt;file&gt;index.html&lt;/file&gt;&lt;file&gt;subfile1.html&lt;/file&gt;&lt;file&gt;subfile.html&lt;/file&gt;&lt;/dir&gt;"]}
    </error>
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.001" name="hty_inte_tests:0 tests_in_fixture (xslpi:basic)">
    <error type="error">
::in function hty_inte:run/2 (src/test/erlang/hty_inte.erl, line 9)
**error:{badmatch,{error,{already_started,&lt;0.85.0&gt;}}}
    </error>
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.014" name="hty_inte_tests:0 tests_in_fixture (catch:status_forward)">
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.009" name="hty_inte_tests:0 tests_in_fixture (storage:loadsave)">
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.010" name="hty_inte_tests:0 tests_in_fixture (static:get_subindex)">
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.010" name="hty_inte_tests:0 tests_in_fixture (static:indextxtaswelcomefile)">
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.010" name="hty_inte_tests:0 tests_in_fixture (static:get_rootfile)">
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.010" name="hty_inte_tests:0 tests_in_fixture (static:get_subfile)">
    <system-out>
    </system-out>
  </testcase>
  <testcase time="0.010" name="hty_inte_tests:0 tests_in_fixture (static:get_rootindex)">
    <system-out>
    </system-out>
  </testcase>
</testsuite>
